//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biographies.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BiosEntities : DbContext
    {
        public BiosEntities()
            : base("name=BiosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<sp_bios_candidates_create_Result> sp_bios_candidates_create(string firstName, string secondName, string lastName, string secondLastName, string shortName, Nullable<System.DateTime> birthDate, string email, string phone, string cellphone, Nullable<int> fOJ, Nullable<int> location, Nullable<int> site, Nullable<int> market, string hashtag)
        {
            var firstNameParameter = firstName != null ?
                new ObjectParameter("FirstName", firstName) :
                new ObjectParameter("FirstName", typeof(string));
    
            var secondNameParameter = secondName != null ?
                new ObjectParameter("SecondName", secondName) :
                new ObjectParameter("SecondName", typeof(string));
    
            var lastNameParameter = lastName != null ?
                new ObjectParameter("LastName", lastName) :
                new ObjectParameter("LastName", typeof(string));
    
            var secondLastNameParameter = secondLastName != null ?
                new ObjectParameter("SecondLastName", secondLastName) :
                new ObjectParameter("SecondLastName", typeof(string));
    
            var shortNameParameter = shortName != null ?
                new ObjectParameter("ShortName", shortName) :
                new ObjectParameter("ShortName", typeof(string));
    
            var birthDateParameter = birthDate.HasValue ?
                new ObjectParameter("BirthDate", birthDate) :
                new ObjectParameter("BirthDate", typeof(System.DateTime));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var phoneParameter = phone != null ?
                new ObjectParameter("Phone", phone) :
                new ObjectParameter("Phone", typeof(string));
    
            var cellphoneParameter = cellphone != null ?
                new ObjectParameter("Cellphone", cellphone) :
                new ObjectParameter("Cellphone", typeof(string));
    
            var fOJParameter = fOJ.HasValue ?
                new ObjectParameter("FOJ", fOJ) :
                new ObjectParameter("FOJ", typeof(int));
    
            var locationParameter = location.HasValue ?
                new ObjectParameter("Location", location) :
                new ObjectParameter("Location", typeof(int));
    
            var siteParameter = site.HasValue ?
                new ObjectParameter("Site", site) :
                new ObjectParameter("Site", typeof(int));
    
            var marketParameter = market.HasValue ?
                new ObjectParameter("Market", market) :
                new ObjectParameter("Market", typeof(int));
    
            var hashtagParameter = hashtag != null ?
                new ObjectParameter("Hashtag", hashtag) :
                new ObjectParameter("Hashtag", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_bios_candidates_create_Result>("sp_bios_candidates_create", firstNameParameter, secondNameParameter, lastNameParameter, secondLastNameParameter, shortNameParameter, birthDateParameter, emailParameter, phoneParameter, cellphoneParameter, fOJParameter, locationParameter, siteParameter, marketParameter, hashtagParameter);
        }
    
        public virtual ObjectResult<sp_bios_candidates_get_Result> sp_bios_candidates_get()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_bios_candidates_get_Result>("sp_bios_candidates_get");
        }
    }
}
